Example:map literal
  void main() {
   var detail={'username':'tom','password','pass@123'};
   print(details);
}
Output
{username:tom,password:pass@123}
Example:adding value to map literals at routine

  void main() {
  var details={'username':'tom','password':'pass@123};
  details['vid']=01001;
  print(details);
}
Output
{username:tom,password:pass@123,vid:01001};
Example:map construction
  void main() {
    var details=newmap();
    details['username']='admin';
    details['password']='admin@123';
    print(details)
}
Output
{username:admin,password:admin@123}


























































