Syantax
  string variables_name='value'
  OR
  string variables_name="value"
  OR 
  string variables_name='''line1 line2'''
  OR
  string variables_name=''''''line1 line2''''''
   
void main() {
  string str1='this is a single line string';
  string str2=''this is a single line string'';
  string str3='''this is a multiline string''';
  string str4=''''this is a multiline string'''';

  print(str1);
  print(str2);
  print(str3);
  print(str4);
Output
  this is a single line string
  this is a single line string 
  this is a multiline line string
  this is a multiline line string

example1
  void nain() {
  string str1=''hello'';
  string str2=''world'';
  string res=str1+str2;

  print("the concatented string:${res}";
}
 example
   void main() {
   int n=1+1;

   string str1="the sum of 1 and 1 is ${n}";
   print (str1);

   string str2="the sum of 2 and 2 is ${2+2}";
   print(str);
 }
  Output
    the sum of 1 and 1 is 2 
    the sum of 2 and 2 is 4
    






  

  
















  
