step2-Initializing
Example 
  void main() {
  var 1st=newlist(3);
  1st[0];
  1st[0];
  1st[2];
  print(1st);
}
Output
[12,13,11]
Growable list
step2-Initializing
Example
   void main () { 
  var num_list={1,2,3}
  print(num_list);
}
Output 
[1,2,3]
Example
   void main () {
   ver 1st=newlist ();
   1st.add(12);
   1st.add(13);
   print(1st);
 ]
Output
[12,13]




























































